### ISSUE TITLE
user_features with continuous values

### ISSUE THREAD

**Issue by simongiles1** [V-Sher/LightFm_HybridRecommenderSystem#1]
Hi,
I apologize if this is the wrong place for a question like this, but I was reading and following along with your article with my own dataset and my features matrix has features that can take on continuous values (i.e. average rating out of 10 (could be 4.329)). What you wrote in your article says to pair every feature with every possible value which isn't possible with continuous values. Would the approach there be to force any continuous feature into a predefined set of bins or is there a method that be more conducive with continuous features?
I would really appreciate your help/thoughts here.
Thanks

**Comment by V-Sher** [comment]
No worries, @simongiles1  :) 

I think what you are dealing with is implicit ratings which need not necessarily be within a fixed 1-10 or 0-5 range. I have had some experience with these (I was using the time spent on a podcast to suggest recommendations to users). What I did was take the continuous values (i.e. time in milliseconds), squished them into a 0-1 range, and then passed them as the `weights` for the `interactions` matrix (something like I have done in the tutorial). Thus, in a way, `time_spent` represents my customers' preference or confidence for a specific podcast. Perhaps you could try something similar.
```
(interactions, weights) = dataset1.build_interactions([(x[0], x[1], x[2]) for x in df.values ])
```

When I wrote "pair each feature with each value" I was talking about creating user/item feature matrices (not the interaction matrix). For example, in my case, I created a user feature matrix because for each user I had information on the podcast genres they liked, their location, and their age category (young, middle, old). And each of these was categorical i.e. the number of possible categories was pre-determined for `genres`, `location`, and `age`. Now in case, I did have the age feature as continuous, I would definitely consider binning it into categories because logically speaking, chances are less that I would find a person of the exact same age as the new user for whom I want to generate some recommendations as part of the cold-start problem. And even if I did find them, they might not even have listened to many podcasts. So better to use a larger pool of users by binning them during training.

Hope this helps!

**Comment by simongiles1** [comment]
Sorry for the delayed response. I was trying to implement everything you were saying and took longer than I thought. Thanks very much super helpful as I have been able to get it running now.
One more question I did have is in the AUC numbers I am getting. In the documentation example:
https://making.lyst.com/lightfm/docs/examples/hybrid_crossvalidated.html
it lists the following AUC values:
CF model: 0.887 train and 0.347 test
Hybrid model: 0.860 train and 0.703 test

In my model I am getting:
CF model: 0.908 train and 0.901 test
Hybrid model: 0.486 train and 0.488 test

The trend in these numbers clearly don't align with what the docs say I should be seeing. I did some research and found that some people suggested that this could imply a warm start issue instead of a cold start. I looked at how sparse the stack exchange dataset is and it is about 99.975% sparse and my dataset is 99.87% sparse. I would assume that that should imply that my dataset isn't suffering from a warm start problem?

Also, one other question I had was, in that link I sent above, what does it mean/what is the model doing when you set the biases to zero?

Thanks again for your help. I really appreciate it.

**Comment by V-Sher** [comment]
IMO, I doubt this has much to do with data sparsity. Based on a quick search through LightFM issue [#486](https://github.com/lyst/lightfm/issues/486#issuecomment-593757379), it seems one of the reasons the CF model works better than the Hybrid model might be the way feature embeddings are summed up under the hood (see [this](https://github.com/lyst/lightfm/issues/486#issuecomment-593757379)). They recommend experimenting with different types of features. Might be worth a shot!

Re the biases, I am not entirely sure but my best guess is that the model calculates some sort of biases (`item_biases`) for each item in your dataset (most probably based on popularity). Setting them to 0 might help you eliminate any such information learned and instead include 'hidden-gems' in the final recommendation list (which otherwise would have contained predominantly the most popular items).
