### ISSUE TITLE
How item-features impact the model?

### ISSUE THREAD

**Issue by Michele971** [V-Sher/LightFm_HybridRecommenderSystem#6]
Hi!
I don't know if this is the right place to make my question. If no, excuse me.
What I would like to know is how the features that a item has can impact the model.
In particular we can imagine that an item has a **category*, a **brand** and a **price**.

So when I fit the model I need to pass the interactions, the weight and the epochs. If I pass item_features then am I considering the  features of the item? This variable will impact the model changing the performances? 

What I understood is that `user_features` are useful when there are new **unknown** users. What about `item_features`? How keep track that item features during the train of the model?

Thanks!

**Comment by V-Sher** [comment]
Hi @Michele971  - In general, adding `user_features` in **addition** to `item_features` during model `fit` should improve the model recommendations. 

>So when I fit the model I need to pass the interactions, the weight, and the epochs. If I pass item_features then am I considering the features of the item? This variable will impact the model changing the performances?

When you `fit` the model, you must pass interactions, weights, epochs, item_features, and user_features. Mainly because the model needs to learn the user and item features during the training process itself. Yes, this variable will impact the model and thus change its performance (hopefully for the better).

> What I understood is that user_features are useful when there are new unknown users. What about item_features? How keep track that item features during the train of the model?

First and foremost, that's not the only time `user_features` are useful. Even for known users, recommendations can be rich if we know about the user traits (like their location, etc.) Regarding `item_features`, you must treat them the same way you treat `user_features` during the training process. These will come in handy for an **item cold-start problem** i.e. one where we have a new incoming item for which we obviously have no interactions but we would still like to find users to whom we can recommend it.

**Comment by Michele971** [comment]
Got it. The problem is that I don’t have user features (except for user_id). Thank you very much!
